// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP1S0c7zDYIG1RONb2tJkUojhXHv_Fork',
    appId: '1:520823482932:web:c5aeeba09b3c6487d23861',
    messagingSenderId: '520823482932',
    projectId: 'turneo-eb22e',
    authDomain: 'turneo-eb22e.firebaseapp.com',
    storageBucket: 'turneo-eb22e.firebasestorage.app',
    measurementId: 'G-D3HGP22QC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx11Ik_99CYG8uGctO-_c9n-yC3Dc94xg',
    appId: '1:520823482932:android:df36770af4561a14d23861',
    messagingSenderId: '520823482932',
    projectId: 'turneo-eb22e',
    storageBucket: 'turneo-eb22e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9Zaz10qrYK48u-NIdlLVzuj7pRfHsNGg',
    appId: '1:520823482932:ios:1b82199f5b77c948d23861',
    messagingSenderId: '520823482932',
    projectId: 'turneo-eb22e',
    storageBucket: 'turneo-eb22e.firebasestorage.app',
    iosBundleId: 'com.bcr.turneo',
  );
}
